### ISSUE TITLE
bug report paper 1.16.5

### ISSUE THREAD

**Issue by FaNt4zMa** [qruet/AnvilLot#10]
For some reasons I am able to combine two protection 1 book at zero cost... The cost is simply not shown 90% of the time. Also the XP bar up top doesnt refresh its count after enchanting something... Should it be gone after closing the anvil? Because it stays there too :(
Otherwise I like the idea and features of this plugin...

**Comment by qruet** [comment]
Sorry for the late response. This is definitely very odd behavior. Make sure you are running off of the latest version of the plugin. Let me know what version your server is on if the issue still persists.

**Comment by TheCiROMG** [comment]
@FaNt4zMa use PurpurMC UwU, Paper is some bug, and AnvilLot is fragile

**Comment by qruet** [comment]
@TheCiROMG Please note that I do not support the use of PurpurMC. Feel free to use it, however, the plugin does not officially support PurpurMC yet and I can not help anyone with any bugs that may come from the use of it.

**Comment by qruet** [comment]
This should have been resolved a while back with the first commit addressing this back in June. Please see
https://github.com/qruet/AnvilLot/commit/0a248c085bc52335463beea9f0c3b6071af90981 for details.
