### ISSUE TITLE
Visual Bug

### ISSUE THREAD

**Issue by niklas2233** [qruet/AnvilLot#11]
**Server Version**
Spigot 1.16.5
**Plugin Version**
AnvilLot 3.4_02-b1
**Describe the bug**
So when i try to enchant my sword with repair cost of 63 when only having 10 level on my charater i get to expensive but when i add so i have 69 levels it works, so i just a visual bug i guess
**To Reproduce**
Steps to reproduce the behavior.
have a sword with alot of enchantments and dont have enough levels to repair/ add enchantment
![2021-02-17_01 14 06](https://user-images.githubusercontent.com/33903786/108138117-97a16a00-70bd-11eb-9a6a-e6d0c7b21d16.png)
![2021-02-17_01 14 11](https://user-images.githubusercontent.com/33903786/108138119-983a0080-70bd-11eb-8e56-f904ad860d5a.png)
![2021-02-17_01 14 37](https://user-images.githubusercontent.com/33903786/108138121-98d29700-70bd-11eb-9894-2c7bd8f161a8.png)

**Comment by qruet** [comment]
A bit confused by the report here. The issue you are describing is intended behavior? When you cannot afford to repair an item (an item that costs 63 levels in your case) a "Too Expensive" message appears along with a boss bar message above showing the cost of the item. When you are able to afford the item the "Too Expensive" message should disappear and the boss bar showing the amount the item costs also disappears. Please let me know if this is the behavior you were seeing.  For now, I will unmark this as a bug but leave this thread open.
