### ISSUE TITLE
Multiple enchantments

### ISSUE THREAD

**Issue by niklas2233** [qruet/AnvilLot#12]
Could you add so you can add all types of protection on the same item and smite and sharpness for example?
Kinda cheaty but i would be happy if you added it

**Comment by qruet** [comment]
Unfortunately, the goal of the plugin is to simply serve as a simple vanilla modification to remove the repair cost cap. I don't want to start adding things that other plugins potentially can do. I know there are many other anvil plugins out there that have these sorts of features. Perhaps if there really isn't an up-to-date solution that you have mentioned here, I may look into making it a separate plugin.
