### ISSUE TITLE
Will there be 1.17 support?

### ISSUE THREAD

**Issue by DerAzubi** [qruet/AnvilLot#17]
Will there be 1.17 support and if so is there a timeline?

PS: Keep up the good work :)

**Comment by qruet** [comment]
Yes there will be support for 1.17. I can't come up with a timeline at the moment however I would expect to release an update fairly soon. Be sure to join the discord to catch live updates from me when a release does come around. 

https://discord.gg/MEuYZVvXkm

**Comment by qruet** [comment]
1.17 support has been added. Check the update out here:
https://www.spigotmc.org/resources/anvillot-%E2%9C%AA-a-limitless-forge-experience-%E2%9C%AA.62905/update?update=410308
