### ISSUE TITLE
Plugin breaks when using java 16

### ISSUE THREAD

**Issue by BigFloppaDev** [qruet/AnvilLot#18]
**Server Version**
Paper

**Plugin Version**
latest
**Describe the bug**
the plugin stops working when using java 16

**Additional context**
i update to java 16 because i need it for 1.17 then the plugin broke

**Comment by qruet** [comment]
Please see latest update that brings support for both Minecraft 1.17 and Java 16. 
https://www.spigotmc.org/resources/anvillot-%E2%9C%AA-a-limitless-forge-experience-%E2%9C%AA.62905/update?update=410308
