### ISSUE TITLE
Does not work properly with Paper 1.18

### ISSUE THREAD

**Issue by Tok3nexe** [qruet/AnvilLot#21]
**Server Version**
What spigot/paper/craftbukkit/etc. version are you using?

-Paper 1.18 #44 (also with older versions I tested)

**Plugin Version**
What version of MaxRepairCost are you using?

-v3.6-b47

**Describe the bug**

-When right-clicking an Anvil, nothing happens, and it throws an error in the console.
-Workaround is clicking without items in both hands and sneaking.

**To Reproduce**
Steps to reproduce the behavior.

-Right-click an anvil 

**Media**
If applicable, add screenshots or a video to help explain your problem.

![image](https://user-images.githubusercontent.com/72341032/144751062-76550e84-053b-46bf-8737-3aefbdf0a903.png)

**Additional context**

**Comment by Gaming32** [comment]
I've already been working on this

**Comment by Gaming32** [comment]
To elaborate here, AnvilLot simply does not have 1.18 support yet. The actual reasons are fairly technical.
