### ISSUE TITLE
1.16 support?

### ISSUE THREAD

**Issue by Kesims** [qruet/AnvilLot#8]
Hello, is there any chance the plugin will be updated in the feature? I really like it andI have been using it, but now it doesnt work on 1.16... Thanks for any answer!

**Comment by qruet** [comment]
Hello Kesims, I am glad that you have been enjoying this plugin. You along with many others have requested for such an update so I have been planning on adding support for 1.16 soon. I have been busy updating some of my other plugins but I should be beginning on adding 1.16 support for AnvilLot finally. You can track my progress and the day I release an update (pre-release) on the community discord: https://discord.gg/fx9gm7T.

**Comment by qruet** [comment]
A pre-release that provides support for 1.16 was just released. I recommend you check it out. ;)
https://github.com/qruet/AnvilLot/releases/tag/3.3_01
